### ISSUE TITLE
Error on capture

### ISSUE THREAD

**Issue by o1ie** [vippsas/vipps-recurring-woocommerce#20]
Hi, getting the following error in sytem log when going to checkout with a subscription product and payment method falls back to another provider.

```
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nb_NO
External object cache: –
Vipps faste betalinger for WooCommerce: av Everyday AS – 1.4.0
Betal med Vipps for WooCommerce: av WP Hosting – 1.4.11
```

```
2020-09-07T11:04:52+00:00 CRITICAL Uncaught Error: Call to undefined function array_key_last() in /home/username/www/no/wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/class-wc-gateway-vipps-recurring.php:876
Stack trace:
#0 /home/username/www/no/wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/class-wc-gateway-vipps-recurring.php(847): WC_Gateway_Vipps_Recurring->capture_payment(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 /home/username/www/no/wp-includes/class-wp-hook.php(289): WC_Gateway_Vipps_Recurring->maybe_capture_payment(21429)
#2 /home/username/www/no/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /home/username/www/no/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/username/www/no/wp-content/plugins/woocommerce/includes/class-wc-order.php(363): do_action('woocommerce_ord...', 21429, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#5 /home/username/www/no/wp-con in /home/username/www/no/wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/class-wc-gateway-vipps-recurring.php on line 876

```

**Comment by Marcuzz** [comment]
Hey,

Thanks for reporting this bug! It appears we were using a function which isn't available in PHP versions prior to 7.3.0. This was unintentional and we have published an update (1.4.1) which fixes this issue for you 😄

**Comment by o1ie** [comment]
Sweet @Marcuzz, thanks for the quick reply :)

**Comment by Marcuzz** [comment]
@o1ie Yeah, unfortunately we can't increase it via the plugin, but we can truncate it.

Version 1.4.2 should have fixed this now 😄

**Comment by Marcuzz** [comment]
@o1ie There you go, 1.4.3 is out and I confirmed it's working this time 😎

**Comment by o1ie** [comment]
Great @Marcuzz, working like a charm 😄  Let me know if you want me to post a separate issue on this for the records.

**Comment by Marcuzz** [comment]
You're welcome 😀

And yeah, sure, a separate issue would be nice 🙂
