### ISSUE TITLE
Fatal error på noe som omhandler prevent_backwards_transition_on_completed_order :-(

### ISSUE THREAD

**Issue by bitrigfix** [vippsas/vipps-recurring-woocommerce#60]
Hei,
Har benyttet Vipps i WooCommerce i noen år nå, og har også knyttet Vipps Faste Betalinger uten problemer. Men, den siste tiden har vi lagt merke til at denne feilen dukket opp når vi forsøker å betale en subscription med Vipps Faste Betalinger:

`Fatal error: Uncaught TypeError: Return value of WC_Gateway_Vipps_Recurring::prevent_backwards_transition_on_completed_order() must be of the type string, null returned in /home/<brukernavn>/public_html/< nettside >.no/wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/wc-gateway-vipps-recurring.php:2031 Stack trace: #0 /home/<brukernavn>/public_html/<nettside>/wp-includes/class-wp-hook.php(307): WC_Gateway_Vipps_Recurring->prevent_backwards_transition_on_completed_order(NULL, 12001, Object(Automattic\WooCommerce\Admin\Overrides\Order)) #1 /home/<brukernavn>/public_html/<nettside>/wp-includes/plugin.php(189): WP_Hook->apply_filters(NULL, Array) #2 /home/<brukernavn>/public_html/<nettside>/wp-content/plugins/woocommerce/includes/class-wc-order.php(119): apply_filters('woocommerce_pay...', 'processing', 12001, Object(Automattic\WooCommerce\Admin\Overrides\Order)) #3 /home/<brukernavn>/public_html/<nettside>.no/wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/wc-gateway-vipps-recurring.php(666): WC_Order in /home/<brukernavn>/public_html/<nettside>.no/wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/wc-gateway-vipps-recurring.php on line 2031`

Kan ikke helt se hva som har endret seg den siste tiden eller hvorfor dette skal dukke opp. Kanskje det er en konflikt med en annen plugin, eller kanskje det er noen customisations vi har gjort som ødelegger for Vipps Faste Betalinger?

Hvor kan vi finne ut av hva som er årsaken uten å måtte "skru fra hverandre" hele nettsiden?

Fantastisk om dere kan bistå slik at vi kan nøste opp i dette. For øyeblikket klarer vi oss fint med Stripe, men vi vil veldig gjerne kunne tilby Vipps Faste Betalinger som et betalingsalternativ til våre kunder.

**Comment by Marcuzz** [comment]
Hei,

Har dere tilfeldigvis egen kode som overskriver `woocommerce_payment_complete_order_status`-filteret? Det som skjer her er at statusen deres for en fullført ordre er `NULL`, men det skal egentlig ikke være mulig å ikke ha en status i dette tilfellet.

Kan du gå til WooCommerce -> Status og hente en "systemrapport" og lime den inn her? 😄

**Comment by bitrigfix** [comment]
Vi bruker WooCommerce Booster og hadde aktivert 2 funksjoner som kanskje ville påvirke:

1. Order Custom Statuses: https://booster.io/features/woocommerce-order-custom-statuses
2. Orders Module: https://booster.io/features/woocommerce-orders

De-aktivering av disse modulene har ikke utgjort noen forskjell. Vi har 1 custom status som en andel ordre har vært merket med tidligere, men som ikke har vært knyttet til Vipps Faste Betalinger gateway. Har gått igjennom functions.php også for å lete etter customisations som kan omhandle dette og der fant vi også en tidligere "auto-complete" kode for renewals av subscriptions. Men den var kommentert ut.

Ok. Mye info i en slik status rapport som man ikke alltid ønsker å publisere, men får heller gå tilbake og slette det hvis det vises seg å være nødvendig (?)


'''
`
### WordPress Environment ###

WordPress address (URL): https://www.bitrigfix.no
Site address (URL): https://www.bitrigfix.no
WC Version: 6.4.1
REST API Version: ✔ 6.4.1
WC Blocks Version: ✔ 7.2.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: nb_NO
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.28
PHP Post Max Size: 512 MB
PHP Time Limit: 180
PHP Max Input Vars: 3000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.37-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.1
WC Database Prefix: wp9f_
Total Database Size: 270.97MB
Database Data Size: 246.93MB
Database Index Size: 24.04MB
wp9f_woocommerce_sessions: Data: 2.21MB + Index: 0.12MB + Engine MyISAM
wp9f_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_woocommerce_order_items: Data: 0.05MB + Index: 0.04MB + Engine MyISAM
wp9f_woocommerce_order_itemmeta: Data: 0.96MB + Index: 0.34MB + Engine MyISAM
wp9f_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp9f_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_actionscheduler_actions: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp9f_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_actionscheduler_logs: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp9f_b2s_posts: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp9f_b2s_posts_drafts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_b2s_posts_favorites: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_b2s_posts_network_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_b2s_posts_sched_details: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp9f_b2s_user: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp9f_b2s_user_contact: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_b2s_user_network_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_cleantalk_ac_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_cleantalk_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_cleantalk_sfw: Data: 0.48MB + Index: 0.36MB + Engine InnoDB
wp9f_cleantalk_sfw_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_cleantalk_spamscan_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_cleantalk_ua_bl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp9f_comments: Data: 0.68MB + Index: 0.29MB + Engine MyISAM
wp9f_csp3_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_cspv5_pages: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp9f_dirsync_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_fiken_orders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp9f_fiken_order_history: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp9f_fiken_states: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_groups_user_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_layerslider: Data: 1.40MB + Index: 0.00MB + Engine MyISAM
wp9f_layerslider_drafts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_layerslider_revisions: Data: 8.27MB + Index: 0.00MB + Engine MyISAM
wp9f_learnpress_order_itemmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp9f_learnpress_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp9f_learnpress_question_answermeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_learnpress_question_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_learnpress_quiz_questions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_learnpress_review_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_learnpress_sections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_learnpress_section_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_learnpress_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_learnpress_user_itemmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp9f_learnpress_user_items: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp9f_learnpress_user_item_results: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_litespeed_crawler: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_litespeed_crawler_blacklist: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp9f_litespeed_img_optm: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
wp9f_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp9f_litespeed_url: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp9f_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp9f_mepr_events: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp9f_mepr_jobs: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp9f_mepr_members: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp9f_mepr_rule_access_conditions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp9f_mepr_subscriptions: Data: 0.02MB + Index: 0.30MB + Engine InnoDB
wp9f_mepr_subscription_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_mepr_tax_rates: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp9f_mepr_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp9f_mepr_transactions: Data: 0.02MB + Index: 0.33MB + Engine InnoDB
wp9f_mepr_transaction_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_mpcs_sections: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp9f_mpcs_user_progress: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp9f_newsletter: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp9f_newsletter_automated: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp9f_newsletter_emails: Data: 1.39MB + Index: 0.00MB + Engine MyISAM
wp9f_newsletter_sent: Data: 0.10MB + Index: 0.15MB + Engine MyISAM
wp9f_newsletter_stats: Data: 0.12MB + Index: 0.08MB + Engine MyISAM
wp9f_newsletter_user_logs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp9f_options: Data: 33.64MB + Index: 0.27MB + Engine MyISAM
wp9f_postmeta: Data: 6.83MB + Index: 2.76MB + Engine MyISAM
wp9f_posts: Data: 138.13MB + Index: 0.60MB + Engine MyISAM
wp9f_redirection_404: Data: 1.02MB + Index: 0.08MB + Engine InnoDB
wp9f_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp9f_redirection_logs: Data: 12.02MB + Index: 1.92MB + Engine InnoDB
wp9f_spbc_auth_logs: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp9f_spbc_backuped_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_spbc_backups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_spbc_bfp_blocked: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_spbc_firewall_data: Data: 4.52MB + Index: 3.52MB + Engine InnoDB
wp9f_spbc_firewall_logs: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp9f_spbc_firewall__personal_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_spbc_firewall__personal_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_spbc_monitoring_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_spbc_scan_frontend: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp9f_spbc_scan_links_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp9f_spbc_scan_results: Data: 5.52MB + Index: 1.52MB + Engine InnoDB
wp9f_spbc_scan_signatures: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp9f_spbc_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_spbc_traffic_control_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_termmeta: Data: 0.05MB + Index: 0.04MB + Engine MyISAM
wp9f_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp9f_term_relationships: Data: 0.03MB + Index: 0.08MB + Engine MyISAM
wp9f_term_taxonomy: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp9f_to_buffer_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp9f_tutor_earnings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_tutor_quiz_attempts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_tutor_quiz_attempt_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_tutor_quiz_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_tutor_quiz_question_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_tutor_withdraws: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_usermeta: Data: 0.26MB + Index: 0.19MB + Engine MyISAM
wp9f_users: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp9f_user_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_vipps_login_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_wcs_payment_retries: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp9f_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp9f_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp9f_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp9f_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp9f_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp9f_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp9f_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_wpfront_ure_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_wpfront_ure_post_type: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_wpfront_ure_taxonomy: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_xyz_ips_short_code: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9f_yoast_indexable: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
wp9f_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp9f_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9f_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9f_yoast_seo_links: Data: 0.18MB + Index: 0.05MB + Engine MyISAM
wp9f_yoast_seo_meta: Data: 0.04MB + Index: 0.04MB + Engine MyISAM

### Post Type Counts ###

attachment: 508
avada_portfolio: 31
awb_off_canvas: 2
courses: 1
fusion_element: 48
fusion_form: 2
fusion_icons: 2
fusion_tb_layout: 9
fusion_tb_section: 12
fusion_template: 7
jetpack_migration: 2
lesson: 5
lp_course: 1
lp_lesson: 10
lp_question: 7
lp_quiz: 3
memberpressproduct: 1
nav_menu_item: 89
oembed_cache: 8
oppslagstavle: 9
page: 91
post: 44
product: 92
product_variation: 275
revision: 4250
shop_coupon: 43
shop_order: 491
shop_order_refund: 3
shop_subscription: 44
slide: 8
spucpt: 2
ticket-meta-fieldset: 4
topics: 5
tribe-ea-record: 2
tribe_events: 44
tribe_organizer: 8
tribe_rsvp_attendees: 158
tribe_rsvp_tickets: 27
tribe_venue: 6
tribe_wooticket: 34
tutor_quiz: 1
wc_memberships_team: 1
wc_membership_plan: 11
wc_user_membership: 68
wc_voucher: 1
wc_voucher_template: 5
wpcf7_contact_form: 3
wp_router_page: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (64) ###

BackupBuddy: by iThemes – 8.7.4.0
LayerSlider: by Kreatura Media – 7.1.4
Bambora Online Checkout: by Bambora – 4.7.2
Booster Plus for WooCommerce: by Pluggabl LLC – 5.5.4
Anti-Spam by CleanTalk: by СleanTalk  – 5.175
Contact Form 7: by Takayuki Miyoshi – 5.5.6
Custom Post Type UI: by WebDevStudios – 1.11.2
miniOrange Directory Sync Add-on: by miniOrange – 2.0
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.4
Event Tickets Plus: by The Events Calendar – 5.4.2
Event Tickets: by The Events Calendar – 5.3.2
The Events Calendar PRO: by The Events Calendar – 5.12.2
Fiken: by Fiken – 1.22
Avada Builder: by ThemeFusion – 3.7
Avada Core: by ThemeFusion – 5.7
Site Kit by Google: by Google – 1.72.0
Groups 404 Redirect: by itthinx – 1.7.0
Groups Restrict Categories: by itthinx – 2.4.0
Groups WooCommerce: by itthinx – 1.28.0
Groups: by itthinx – 2.16.1
Image Map Pro: by Webcraft Plugins Ltd. – 5.3.2
Instant Images: by Darren Cooney – 4.6.1
Itthinx Updates: by itthinx – 1.4.0
Klarna Order Management for WooCommerce: by klarna
krokedil – 1.6.10

Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.9.0

LDAP/Active Directory Login for Intranet Sites: by miniOrange – 24.1
LiteSpeed Cache: by LiteSpeed Technologies – 4.6
Loco Translate: by Tim Whitlock – 2.6.1
Media File Renamer: by Jordy Meow – 5.3.8
miniOrange Password Sync with LDAP Server Add-on: by miniOrange – 2.0
miniOrange Third Party User Profile Integration with LDAP Add-on: by miniOrange – 2.0
Nav Menu Roles: by Kathy Darling – 2.1.0
Newsletter - Contact Form 7: by The Newsletter Team – 4.1.4
Newsletter - Subscribe on Comments: by The Newsletter Team – 1.0.7
Newsletter - Addons Manager: by The Newsletter Team – 1.1.8
Newsletter - Instasend (BETA): by The Newsletter Team – 1.0.2
Newsletter - Reports: by The Newsletter Team – 4.3.1
Newsletter - WooCommerce: by The Newsletter Team – 1.4.2
Newsletter: by Stefano Lissa & The Newsletter Team – 7.4.2
Page Links To: by Mark Jaquith – 3.3.6
Permalink Manager Lite: by Maciej Bis – 2.2.17
PixelYourSite: by PixelYourSite – 8.2.18
Redirection: by John Godley – 5.2.3
Restrict Usernames Emails Characters: by benaceur – 2.9.7
Simple Image Sizes: by Rahe – 3.2.1
The Events Calendar: Community Events: by The Events Calendar – 4.8.13
The Events Calendar Shortcode & Block: by Event Calendar Newsletter – 2.5.2
The Events Calendar: by The Events Calendar – 5.14.1
Timed Content: by K. Tough
Arno Welzel
Enrico Bacis – 2.68

Event Tickets Extension: Organizer Notifications: by Modern Tribe
Inc. – 1.0.0

Tutor LMS: by Themeum – 2.0.1
Vipps Recurring Payments Gateway for WooCommerce: by Everyday AS – 1.13.4
Product Customer List for WooCommerce: by Kokomo – 3.0.6
Checkout with Vipps for WooCommerce: by WP Hosting – 1.8.20
WooCommerce Stripe Gateway: by WooCommerce – 6.3.0
WooCommerce Group Coupons: by itthinx – 1.24.1
Booster for WooCommerce: by Pluggabl LLC – 5.5.6
WooCommerce Subscriptions - Do Not Reduce Stock on Renewal: by Prospress Inc. –
WooCommerce Subscriptions - Preserve Billing Schedule: by Prospress Inc. – 1.0.0
WooCommerce Subscriptions: by WooCommerce – 4.1.0
WooCommerce: by Automattic – 6.4.1
miniOrange WP Groups Plugin Integration Add-on: by miniOrange – 1.0
WPFront User Role Editor: by Syam Mohan – 3.2.1.11184
YotuWP - YouTube Gallery: by  – 1.3.4.5

### Inactive Plugins (11) ###

Custom Post Type Permalinks: by Toro_Unit – 3.4.5
Fusion Builder Custom Post Types and Taxonomies: by Amunet – 6.2
Insert PHP Code Snippet: by xyzscripts.com – 1.3.3
Login with Vipps: by WP-Hosting AS – 1.1.21
SeedProd Coming Soon Page Pro: by SeedProd – 5.11.7
Simple Local Avatars: by Jake Goldman
10up – 2.2.0

SKU Shortlink For WooCommerce: by Varun Sridharan – 1.4
User Role Editor: by Vladimir Garagulya – 4.61.2
Wph Vipps Login And Do: by iverok – 1.0.0
WP Maintenance Mode & Coming Soon: by Themeisle – 2.4.4
Yoast SEO: by Team Yoast – 18.5.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: NOK (kr)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7 - /bestill/
Cart: #8 - /bestilling/
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #10 - /brukerkonto/
Terms and conditions: #58 - /vilkar-og-betingelser/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.7
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada-Child-Theme/woocommerce/myaccount/dashboard.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php


### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://www.bitrigfix.no
Subscription Statuses: trash: 4
wc-active: 4
wc-expired: 2
wc-pending: 1
wc-on-hold: 1
wc-cancelled: 32

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Norway

### Subscriptions by Payment Gateway ###

other: wc-active: 2
wc-cancelled: 21
wc-expired: 2

Check payments: wc-cancelled: 6
Stripe: wc-active: 2
Vipps Recurring Payments: trash: 4
wc-cancelled: 1
wc-pending: 1


### Payment Gateway Support ###

Vipps Recurring Payments: subscriptions
refunds
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin

Vipps: products
refunds

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

Check payments: products
Cash on delivery: products
Nesodden Makerspace sender eFaktura: products

### Klarna Payments Request Log ###

2022-03-13 20:41:01: KP Update Session
Response code: 404
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"NOT_FOUND\",\n  \"error_messages\" : [ \"Invalid session id\" ],\n  \"correlation_id\" : \"dbdeef3f-fc25-4ad9-b99e-b68ccc32da8f\"\n}","response":{"code":404,"message":"Not Found"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-01-22 22:03:00: KP Update Session
Response code: 404
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"NOT_FOUND\",\n  \"error_messages\" : [ \"Invalid session id\" ],\n  \"correlation_id\" : \"07d38ea7-60fa-4b10-875b-6b8ff65505ac\"\n}","response":{"code":404,"message":"Not Found"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:


### Klarna Countries ###

Production Countries: NO
Test Countries: No countries selected

### Action Scheduler ###

Canceled: 2
Oldest: -0001-11-30 00:43:00 +0043
Newest: -0001-11-30 00:43:00 +0043

Complete: 401
Oldest: 2022-03-22 08:11:31 +0100
Newest: 2022-04-21 15:13:32 +0200

Failed: 1
Oldest: –
Newest: –

Pending: 7
Oldest: 2022-04-21 15:24:17 +0200
Newest: 2022-07-29 14:09:35 +0200


### Status report information ###

Generated at: 2022-04-21 15:19:31 +02:00
`
'''

**Comment by Marcuzz** [comment]
Jeg slettet statusrapporten nå som jeg har kopiert den et annet sted. Det ble uansett unødvendig nå som jeg vet at dere bruker et par utvidelser som kan ha noe å si på hvordan statuser fungerer.

Undersøker litt nærmere og finner ut av den mest passende fiksen. Jeg kommer tilbake til deg når jeg har en løsning.

**Comment by Marcuzz** [comment]
Prøv versjon 1.14.0, si gjerne i fra dersom det ikke fikser problemet du opplever :)
