### ISSUE TITLE
Multiple Cron job errors

### ISSUE THREAD

**Issue by Haldaug** [vippsas/vipps-recurring-woocommerce#67]
I get the following errors in my error log from vipps-recurring-woocommerce:
```
[11-Jan-2023 01:47:38 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /home/energmrl/public_html/wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/wc-gateway-vipps-recurring.php:629
Stack trace:
#0 /home/energmrl/public_html/wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/woo-vipps-recurring.php(710): WC_Gateway_Vipps_Recurring->check_charge_status()
#1 /home/energmrl/public_html/wp-includes/class-wp-hook.php(308): WC_Vipps_Recurring->check_order_statuses()
#2 /home/energmrl/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#3 /home/energmrl/public_html/wp-includes/plugin.php(565): WP_Hook->do_action()
#4 /home/energmrl/public_html/wp-cron.php(188): do_action_ref_array()
#5 {main}
  thrown in /home/energmrl/public_html/wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/wc-gateway-vipps-recurring.php on line 629
```
```
[12-Jan-2023 08:52:21 UTC] Cron-feil ved gjenplanlegging av hendelse for krok: woocommerce_vipps_recurring_check_gateway_change_request, feilkode: could_not_set, feilmelding: Cron-hendelseslisten kunne ikke lagres., data: {"schedule":"one_minute","args":[],"interval":60}
[12-Jan-2023 08:52:21 UTC] Cron-feil ved fjerning av planlagt hendelse for krok: woocommerce_vipps_recurring_check_gateway_change_request, feilkode: could_not_set, feilmelding: Cron-hendelseslisten kunne ikke lagres., data: {"schedule":"one_minute","args":[],"interval":60}
```

This results in reaching the resource limits on my server.

**Comment by Marcuzz** [comment]
Hi,

Is this issue still occurring? We made a big update recently that updated the entire way we handle data

**Comment by Marcuzz** [comment]
I'm closing this issue due to inactivity. Please re-open it if the issue still occurs 😄
